# Generated by Django 4.0.4 on 2022-04-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_remove_concept_location_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='ocurrences',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
