# Generated by Django 4.0.4 on 2022-05-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_church_shepherd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='local_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
