# Generated by Django 4.0.4 on 2022-06-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_person_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='min_licenciado',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='min_ordenado',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='obrero_exhortador',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='obrero_inicial',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='obrero_licenciado',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
