# Generated by Django 4.0.4 on 2022-07-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_person_min_licenciado_person_min_ordenado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='zone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
