# Generated by Django 4.0.4 on 2023-04-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_church_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attendance',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
