# Generated by Django 4.0.4 on 2023-04-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_remove_user_attendance_person_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='attendance',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
