# Generated by Django 4.0.4 on 2023-07-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_alter_person_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
