# Generated by Django 4.0.4 on 2023-07-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_person_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='min_licenciado',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='person',
            name='church',
        ),
        migrations.RemoveField(
            model_name='person',
            name='min_ordenado',
        ),
        migrations.RemoveField(
            model_name='person',
            name='obrero_exhortador',
        ),
        migrations.RemoveField(
            model_name='person',
            name='obrero_inicial',
        ),
        migrations.RemoveField(
            model_name='person',
            name='obrero_licenciado',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='cellphone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='civil_status',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='disease',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='doctor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='ocupation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='reason_consultation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
