# Generated by Django 4.0.4 on 2024-03-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_attendance_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
