# Generated by Django 4.0.4 on 2026-06-13 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_alter_attendance_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(verbose_name=datetime.date(2026, 6, 20)),
        ),
    ]
