# Generated by Django 4.0.4 on 2022-04-22 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_concept_ocurrences'),
        ('entries', '0002_rename_reference_entry_note_remove_entry_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.church'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.person'),
        ),
    ]
