# Generated by Django 4.0.4 on 2022-04-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_alter_entry_church_alter_entry_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
