# Generated by Django 4.0.4 on 2022-05-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_item_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
