# Generated by Django 4.0.4 on 2022-06-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_alter_entry_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='period_month',
            field=models.PositiveSmallIntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='period_year',
            field=models.PositiveSmallIntegerField(default=2022),
            preserve_default=False,
        ),
    ]
