# Generated by Django 4.0.4 on 2022-12-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_item_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
